### ISSUE TITLE
fps cap doesn't work

### ISSUE THREAD

**Issue by Vortex2Oblivion** [swordcube/FNF-Genesis-Engine#18]
![image](https://user-images.githubusercontent.com/73261680/206910743-7f2c5247-da1d-4a78-822d-20711f5234d7.png)
either that or the fps counter is broken

**Comment by swordcube** [comment]
Does it work when changing the value or does it just not work at all

**Comment by Vortex2Oblivion** [comment]
it works when changing the value, but the fps in the counter can go like 100 above the cap

**Comment by swordcube** [comment]
openfl's fps counter is stupid as hell

**Comment by Vortex2Oblivion** [comment]
understandable, have a nice day
