### ISSUE TITLE
No linux? :(

### ISSUE THREAD

**Issue by Teuxml** [swordcube/FNF-Genesis-Engine#2]
The game crashes when i build it on arch linux.
I get this crash log: 

Uncaught Error: [file_contents,/home/teu/Ãrea de trabalho/Funkin'/FNF-Genesis-Engine/export/release/linux/bin/mods/home/modInfo.json]

**Comment by swordcube** [comment]
"mods/home/modInfo.json"

hold on what the fuck how did that get there

**Comment by swordcube** [comment]
> The game crashes when i build it on arch linux. I get this crash log:
> 
> Uncaught Error: [file_contents,/home/teu/Ã�rea de trabalho/Funkin'/FNF-Genesis-Engine/export/release/linux/bin/mods/home/modInfo.json]

wait i use arch linux to test too, what the fuck?
