### ISSUE TITLE
could not open the game on (Macos)

### ISSUE THREAD

**Issue by JonnycatMeow** [swordcube/FNF-Genesis-Engine#9]
![Screen Shot 2022-10-17 at 5 21 35 PM](https://user-images.githubusercontent.com/107599365/196307137-feb68063-dd54-4083-b880-a5ee299b32b4.png)

**Comment by itsDARK768** [comment]
You may have just fucked up your copy, redownload the game and if the issue continues
Use wine to launch the windows version

**Comment by swordcube** [comment]
I don't know how to fix this issue since i do not own a Mac, I only have a Windows computer (dualbooted with linux), so i cannot test for issues. However you can use Wine to run the Windows version as mentioned above.
